// Listing-related schemas: Listing, CreateListingInput, TransitionInput, GeoPoint, PropertyType.

export const listingSchemas: Record<string, unknown> = {
  GeoPoint: {
    type: "object",
    properties: {
      type: { type: "string", enum: ["Point"], default: "Point" },
      coordinates: {
        type: "array",
        items: { type: "number" },
        minItems: 2,
        maxItems: 2,
        example: [13.405, 52.52],
        description: "[longitude, latitude]",
      },
    },
  },
  PropertyType: {
    type: "string",
    enum: [
      "apartment",
      "house",
      "villa",
      "condominium",
      "land",
      "commercial_space",
      "office",
      "warehouse",
      "shop",
      "mixed_use",
    ],
  },
  Listing: {
    type: "object",
    properties: {
      id: { type: "string" },
      title: { type: "string" },
      description: { type: "string" },
      listingType: { type: "string", enum: ["sale", "rent"] },
      category: { type: "string", enum: ["residential", "commercial"] },
      propertyType: { $ref: "#/components/schemas/PropertyType" },
      status: {
        type: "string",
        enum: [
          "draft",
          "submitted",
          "under_review",
          "approved",
          "rejected",
          "published",
          "suspended",
          "rented",
          "sold",
          "archived",
        ],
      },
      availabilityStatus: {
        type: "string",
        enum: ["available", "under_offer", "rented", "sold"],
      },
      price: { type: "number" },
      monthlyRent: { type: "number" },
      currency: { type: "string", example: "USD" },
      bedrooms: { type: "integer" },
      bathrooms: { type: "integer" },
      area: {
        type: "object",
        properties: {
          value: { type: "number" },
          unit: { type: "string", enum: ["sqm", "sqft"], default: "sqm" },
        },
      },
      yearBuilt: { type: "integer" },
      floorNumber: { type: "integer" },
      parkingSpaces: { type: "integer" },
      totalFloors: { type: "integer" },
      maintenanceFee: { type: "number" },
      serviceCharge: { type: "number" },
      furnishingStatus: {
        type: "string",
        enum: ["furnished", "semi_furnished", "unfurnished"],
      },
      utilityDetails: { type: "string" },
      neighborhoodInfo: { type: "string" },
      nearbyLandmarks: { type: "array", items: { type: "string" } },
      rentalTerms: { type: "string" },
      saleTerms: { type: "string" },
      legalNotes: { type: "string" },
      address: {
        type: "object",
        properties: {
          street: { type: "string" },
          city: { type: "string" },
          region: { type: "string" },
          country: { type: "string" },
          postalCode: { type: "string" },
        },
      },
      location: { $ref: "#/components/schemas/GeoPoint" },
      amenities: { type: "array", items: { type: "string" } },
      photos: {
        type: "array",
        items: {
          type: "object",
          properties: {
            url: { type: "string" },
            publicId: { type: "string" },
            isCover: { type: "boolean" },
          },
        },
      },
      verificationStatus: {
        type: "string",
        enum: [
          "unverified",
          "pending",
          "requires_more_info",
          "verified",
          "rejected",
          "suspended",
        ],
      },
      tokenId: { type: "string", nullable: true },
      createdBy: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateListingInput: {
    type: "object",
    required: ["title", "listingType", "category", "propertyType", "location"],
    properties: {
      title: { type: "string", maxLength: 200 },
      description: { type: "string", maxLength: 5000 },
      listingType: { type: "string", enum: ["sale", "rent"] },
      category: { type: "string", enum: ["residential", "commercial"] },
      propertyType: { $ref: "#/components/schemas/PropertyType" },
      price: {
        type: "number",
        minimum: 0,
        description:
          "Required when listingType=sale; forbidden when listingType=rent",
      },
      monthlyRent: {
        type: "number",
        minimum: 0,
        description:
          "Required when listingType=rent; forbidden when listingType=sale",
      },
      currency: {
        type: "string",
        minLength: 3,
        maxLength: 3,
        default: "USD",
        description: "ISO 4217 code, uppercased",
      },
      bedrooms: { type: "number", minimum: 0 },
      bathrooms: { type: "number", minimum: 0 },
      area: {
        type: "object",
        required: ["value"],
        properties: {
          value: { type: "number", minimum: 0 },
          unit: { type: "string", enum: ["sqm", "sqft"], default: "sqm" },
        },
      },
      yearBuilt: { type: "integer", minimum: 1800, maximum: 2100 },
      floorNumber: { type: "integer", minimum: 0 },
      parkingSpaces: { type: "integer", minimum: 0 },
      totalFloors: { type: "integer", minimum: 0 },
      maintenanceFee: { type: "number", minimum: 0 },
      serviceCharge: { type: "number", minimum: 0 },
      utilityDetails: { type: "string", maxLength: 2000 },
      neighborhoodInfo: { type: "string", maxLength: 2000 },
      furnishingStatus: {
        type: "string",
        enum: ["furnished", "semi_furnished", "unfurnished"],
      },
      nearbyLandmarks: {
        type: "array",
        items: { type: "string", maxLength: 200 },
      },
      rentalTerms: { type: "string", maxLength: 5000 },
      saleTerms: { type: "string", maxLength: 5000 },
      legalNotes: { type: "string", maxLength: 5000 },
      address: {
        type: "object",
        properties: {
          street: { type: "string" },
          city: { type: "string" },
          region: { type: "string" },
          country: { type: "string" },
          postalCode: { type: "string" },
        },
      },
      location: { $ref: "#/components/schemas/GeoPoint" },
      amenities: { type: "array", items: { type: "string" } },
    },
  },
  TransitionInput: {
    type: "object",
    required: ["action"],
    properties: {
      action: {
        type: "string",
        enum: [
          "submit",
          "start_review",
          "request_info",
          "approve",
          "reject",
          "publish",
          "suspend",
          "unsuspend",
          "mark_rented",
          "mark_sold",
          "unmark_rented",
          "unmark_sold",
          "archive",
        ],
      },
      reason: {
        type: "string",
        enum: [
          "missing_document",
          "invalid_ownership_proof",
          "wrong_location",
          "poor_quality",
          "suspicious",
          "duplicate",
          "other",
        ],
        description: "Required when action=reject",
      },
      note: {
        type: "string",
        maxLength: 2000,
        description: "Required when action=request_info or suspend",
      },
    },
  },
  BulkActionInput: {
    type: "object",
    required: ["actions"],
    properties: {
      actions: {
        type: "array",
        minItems: 1,
        maxItems: 50,
        items: {
          type: "object",
          required: ["id", "action"],
          properties: {
            id: { type: "string", description: "24-char hex Mongo ObjectId" },
            action: {
              type: "string",
              enum: [
                "submit",
                "start_review",
                "request_info",
                "approve",
                "reject",
                "publish",
                "suspend",
                "unsuspend",
                "mark_rented",
                "mark_sold",
                "unmark_rented",
                "unmark_sold",
                "archive",
              ],
            },
            reason: {
              type: "string",
              enum: [
                "missing_document",
                "invalid_ownership_proof",
                "wrong_location",
                "poor_quality",
                "suspicious",
                "duplicate",
                "other",
              ],
              description: "Required when action=reject",
            },
            note: { type: "string", maxLength: 2000 },
          },
        },
      },
    },
  },
  DocumentUploadType: {
    type: "string",
    enum: [
      "title_deed",
      "tax_record",
      "utility_bill",
      "ownership_certificate",
      "lease_authority",
      "government_document",
      "other",
    ],
    default: "other",
    description: "Property-related document type. Identity docs belong to KYC.",
  },
};
